version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: .\build.ps1
cache:
  - tools\Cake -> tools\packages.config # Cake NuGet cache
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'  # NuGet Cache
  - src\Frontend\node_modules -> src\Frontend\package.json
test: off
